name: ejercicio1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  google_fonts: ^6.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/login/
    - assets/uber/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Creating Graphics Demo.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700